//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuonTaiLieu
    {
        public string MaVach { get; set; }
        public string MaTL { get; set; }
    
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
