//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiLieu()
        {
            this.CuonTaiLieux = new HashSet<CuonTaiLieu>();
        }
    
        public string MaTL { get; set; }
        public string TenTL { get; set; }
        public string MaLTL { get; set; }
        public string MaNgonNgu { get; set; }
        public string MaNXB { get; set; }
        public System.DateTime NamXuatBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TacGia { get; set; }
        public System.DateTime NgayCN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuonTaiLieu> CuonTaiLieux { get; set; }
        public virtual LoaiTaiLieu LoaiTaiLieu { get; set; }
        public virtual NgonNgu NgonNgu { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
    }
}
